apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-service
  template:
    metadata:
      labels:
        app: telemetry-service
    spec:
      containers:
        - name: telemetry-service
          image: vehicle-telematics-api-telemetry-service:latest
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
spec:
  selector:
    app: telemetry-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
